apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-secrets-config
  namespace: argocd
  labels:
    app.kubernetes.io/part-of: external-secrets
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  project: default
  source:
    repoURL: https://github.com/igorsilva-dev/k8s-gitops
    targetRevision: main
    path: external-secrets/config
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: external-secrets
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    retry:
      limit: 10
      backoff:
        duration: 30s
        maxDuration: 5m
        factor: 2
