apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: doppler
  labels:
    app.kubernetes.io/part-of: external-secrets
spec:
  provider:
    doppler:
      auth:
        secretRef:
          dopplerToken:
            name: doppler-token-auth-api
            namespace: external-secrets
            key: dopplerToken
      project: k8s-codeup
      config: dev
