apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: sandbox-demo
  namespace: sandbox
  labels:
    app.kubernetes.io/part-of: external-secrets
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: doppler
    kind: ClusterSecretStore
  target:
    name: sandbox-demo
    creationPolicy: Owner
  data:
    - secretKey: TEST_SECRET
      remoteRef:
        key: TEST_SECRET
